server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 100MB        # 单个文件最大大小
      max-request-size: 100MB     # 单次请求最大大小
      enabled: true               # 启用文件上传
      file-size-threshold: 0      # 内存中文件阈值
  datasource:
    url: jdbc:mysql://localhost:3306/interview_system?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    password: 797789
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20

ffmpeg:
#  path: /usr/local/bin/ffmpeg  # Linux/macOS
   path: D:\\Program File (x86)\\ffmpeg\\bin\\ffmpeg.exe  # Windows




mybatis-plus:
  type-aliases-package: com.little bug.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      table-prefix: news_ # 设置表的前缀

#jwt??
jwt:
  token:
    tokenExpiration: 120 #????,????
    tokenSignKey: Interview123456  #不是UTF-8？

swagger:
  enabled: true